/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftjoin;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Set;

public class LeftJoin {
    public ArrayList<String> leftJoin(Hashtable<String,String> HTLeft, Hashtable<String,String> HTRight) {
        Set<String> leftKeys = HTLeft.keySet();
        ArrayList<String> leftJoined = new ArrayList<>();
        return null;
    }
}
