/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.Test;
import static org.junit.Assert.*;

public class GraphTest {
    @Test public void testSomeLibraryMethod() {
        Graph classUnderTest = new Graph();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
