/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leftjoin;

import org.junit.Before;
import org.junit.Test;

import java.util.Hashtable;

import static org.junit.Assert.*;

public class LeftJoinTest {
    @Test
    public void testInstantiate() {
        LeftJoin join = new LeftJoin();
    }

    LeftJoin join;
    Hashtable<String,String> HTLeft;
    Hashtable<String,String> HTRight;

    @Before
    public void setUp() {
        join = new LeftJoin();
        HTLeft = new Hashtable<>();
        HTRight = new Hashtable<>();
        HTLeft.put("a", "hi");
        HTLeft.put("b", "hello");
        HTLeft.put("c", "hey");
        HTLeft.put("d", "heyo");
        HTRight.put("a", "sup");
        HTRight.put("b", "yo");
        HTRight.put("c", "ayo");
        HTRight.put("e", "watup");
        HTRight.put("f", "litty");
    }

//    @Test
//    public void testIfReadingHT1() {
//        join.leftJoin(HTLeft, HTRight);
//    }



}
